
CREATE TABLE IF NOT EXISTS "User"(
  "UserID" INTEGER PRIMARY KEY NOT NULL,
  "UserName" VARCHAR(20) NOT NULL,
  "PasswordHash" VARCHAR(100) NOT NULL,
  "DailyKiloJouleGoal" INTEGER DEFAULT 8368
);

CREATE TABLE IF NOT EXISTS "Meal" (
  "MealID" INTEGER PRIMARY KEY NOT NULL,
  "UserID" INTEGER NOT NULL,
  "Time" TIMESTAMP NOT NULL,
  FOREIGN KEY("UserID") REFERENCES "User"("UserID")
  ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "FoodNameFi"(
  "FoodID" INTEGER PRIMARY KEY NOT NULL,
  "FoodName" VARCHAR(50) NOT NULL,
  "Lang" VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS "InAMeal"(
  "MealID" INTEGER NOT NULL,
  "FoodID" INTEGER NOT NULL,
  "Amount" VARCHAR(30) NOT NULL,
  FOREIGN KEY("MealID") REFERENCES "Meal"("MealID")
  ON DELETE CASCADE,
  FOREIGN KEY("FoodID") REFERENCES "FoodNameFi"("FoodID")
  ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Component"(
  "EUFDNAME" VARCHAR(15) PRIMARY KEY NOT NULL,
  "COMPUNIT" VARCHAR(5)  NOT NULL,
  "CMPCLASS" VARCHAR(10) NOT NULL,
  "CMPCLASSP" VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS "ComponentValue"(
  "FoodID" INTEGER NOT NULL,
  "EUFDNAME" VARCHAR(15) NOT NULL,
  "BESTLOC" VARCHAR(30) NOT NULL,
  PRIMARY KEY ("FoodID", "EUFDNAME"),
  FOREIGN KEY("FoodID") REFERENCES "FoodNameFi"("FoodID")
  ON DELETE CASCADE,
  FOREIGN KEY("EUFDNAME") REFERENCES "Component"("EUFDNAME")
  ON DELETE CASCADE,
  UNIQUE("FoodID", "EUFDNAME")
);
